#!/usr/bin/env python3
"""Collect and analyze R016 (Opus 5 on the R015 features).

    python3 score.py collect   # read the 5 session roots -> ../artifacts/assignments.csv, sessions.csv
    python3 score.py analyze   # compare with R015's assignments -> ../artifacts/results.md

The analysis is fixed in protocol.md and was committed before any session ran.
The comparison sessions are R015's (same features, prompt and menu). Standard
library only, seeded.
"""

from __future__ import annotations

import csv
import datetime
import importlib.util
import os
import random
import sys
from collections import Counter
from pathlib import Path
from statistics import mean

HERE = Path(__file__).resolve().parent
ITEM = HERE.parent
R015 = ITEM.parent / "R015-crew-preference-across-five-orchestrators-and-five-features"
ASSIGNMENTS = ITEM / "artifacts" / "assignments.csv"
SESSION_TIMES = ITEM / "artifacts" / "sessions.csv"
RESULTS = ITEM / "artifacts" / "results.md"

SEED = 16
N_PERM = 100_000

# R015's scorer holds the menu, provider map, Orbit reading and log parsing.
_spec = importlib.util.spec_from_file_location("r015", R015 / "code" / "score.py")
r015 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(r015)
MENU, PROVIDER, FEATURES = r015.MENU, r015.PROVIDER, r015.FEATURES
OTHERS = ["astra", "gemini-flash", "grok", "sol"]  # R015's non-Anthropic orchestrators
ANTHROPIC_SHARE = r015.MENU_SHARE["anthropic"]


def collect() -> None:
    os.environ.setdefault("CREW_PREF_ORBIT_BASE", os.path.expanduser("~/.orbit-crew-pref-r016"))
    r015.SESSIONS = HERE / "sessions.tsv"
    r015.ASSIGNMENTS = ASSIGNMENTS
    r015.ITEM = ITEM
    r015.SESSION_TIMES = SESSION_TIMES
    r015.collect()  # also writes sessions.csv from ../output


def rows_by_feature():
    """{feature: {label: [valid rows]}} with label 'opus-5', 'opus-5.5' or an R015 orchestrator."""
    with ASSIGNMENTS.open() as f:
        new = [r for r in csv.DictReader(f) if r["valid"] == "1"]
    with (R015 / "artifacts" / "assignments.csv").open() as f:
        old = [r for r in csv.DictReader(f) if r["valid"] == "1"]
    out = {feat: {} for feat in FEATURES}
    for r in new:
        out[r["feature"]].setdefault("opus-5", []).append(r)
    for r in old:
        label = "opus-5.5" if r["orchestrator"] == "opus" else r["orchestrator"]
        out[r["feature"]].setdefault(label, []).append(r)
    return out


def share(rows, key, value) -> float:
    return sum(r[key] == value for r in rows) / len(rows)


def d_stat(cells, label, key, value, labels_by_feat) -> float:
    """Mean over features of (label's share) minus mean share of OTHERS."""
    diffs = []
    for feat in FEATURES:
        m = labels_by_feat[feat]
        own = share(cells[feat][m[label]], key, value)
        diffs.append(own - mean(share(cells[feat][m[o]], key, value) for o in OTHERS))
    return mean(diffs)


def perm_test(cells, key, value) -> tuple[float, float]:
    """One-sided: shuffle labels among Opus 5 and the four R015 others within feature."""
    pool = ["opus-5", *OTHERS]
    ident = {f: {x: x for x in pool} for f in FEATURES}
    obs = d_stat(cells, "opus-5", key, value, ident)
    rng = random.Random(SEED)
    ge = 0
    for _ in range(N_PERM):
        labels = {}
        for f in FEATURES:
            shuffled = pool[:]
            rng.shuffle(shuffled)
            labels[f] = dict(zip(pool, shuffled))
        ge += d_stat(cells, "opus-5", key, value, labels) >= obs - 1e-12
    return obs, (1 + ge) / (1 + N_PERM)


def version_test(cells) -> tuple[list, float, float]:
    """Opus 5 minus Opus 5.5 Anthropic share per feature; exact two-sided sign-flip."""
    diffs = [share(cells[f]["opus-5"], "crew_provider", "anthropic")
             - share(cells[f]["opus-5.5"], "crew_provider", "anthropic") for f in FEATURES]
    obs = mean(diffs)
    flips = [mean(s * d for s, d in zip(signs, diffs))
             for signs in __import__("itertools").product([1, -1], repeat=len(diffs))]
    p = sum(abs(x) >= abs(obs) - 1e-12 for x in flips) / len(flips)
    return diffs, obs, p


def analyze() -> None:
    cells = rows_by_feature()
    fp, table, pct = r015.fp, r015.table, r015.pct
    L = ["# R016 results", "",
         f"Generated by `code/score.py analyze` from `artifacts/assignments.csv` and R015's. "
         f"Seed {SEED}, {N_PERM:,} permutations.", ""]

    new = [r for f in FEATURES for r in cells[f]["opus-5"]]
    comp = []
    with ASSIGNMENTS.open() as f:
        allrows = list(csv.DictReader(f))
    for feat in FEATURES:
        rs = [r for r in allrows if r["feature"] == feat]
        comp.append([feat, len(rs), sum(r["valid"] == "1" for r in rs),
                     sum(not r["crew_reason"] for r in rs),
                     sum(r["status"] != "proposed" for r in rs)])
    L += ["## 1. Compliance", "", table(["Feature", "Tasks", "Menu crew", "No reason", "Not proposed"], comp), ""]

    d, p = perm_test(cells, "crew_provider", "anthropic")
    L += ["## 2. Primary: Opus 5 against the non-Anthropic orchestrators", "",
          "d = Opus 5's Anthropic share minus the mean Anthropic share of R015's astra, "
          "gemini-flash, grok and sol on the same feature, averaged over features. One-sided "
          "permutation test, labels shuffled within feature among those five sessions.", "",
          f"**d = {d:+.3f}, one-sided p = {fp(p)}.**", ""]

    diffs, obs, pv = version_test(cells)
    rows = [[f, pct(share(cells[f]["opus-5"], "crew_provider", "anthropic")),
             pct(share(cells[f]["opus-5.5"], "crew_provider", "anthropic")),
             pct(mean(share(cells[f][o], "crew_provider", "anthropic") for o in OTHERS)),
             f"{x:+.2f}"] for f, x in zip(FEATURES, diffs)]
    L += ["## 3. Secondary: Opus 5 against Opus 5.5", "",
          table(["Feature", "Opus 5", "Opus 5.5 (R015)", "Others (R015 mean)", "5 minus 5.5"], rows), "",
          f"Mean difference {obs:+.3f}; exact two-sided sign-flip test over the five features, "
          f"p = {pv:.3f} (the smallest possible is {2 / 32:.3f}).", ""]

    d_c, p_c = perm_test(cells, "crew", "opus")
    own = sum(r["crew_provider"] == "anthropic" for r in new)
    L += ["## 4. Secondary", "",
          f"- Own-crew (`opus`) d = {d_c:+.3f}, one-sided p = {fp(p_c)}.",
          f"- Lift against the menu: {own}/{len(new)} Anthropic, expected "
          f"{len(new) * ANTHROPIC_SHARE:.1f}, lift {own / len(new) / ANTHROPIC_SHARE:.2f}.", ""]

    c5 = Counter(r["crew"] for r in new)
    c55 = Counter(r["crew"] for f in FEATURES for r in cells[f]["opus-5.5"])
    L += ["## 5. Descriptive", "",
          table(["Orchestrator", *MENU, "n"],
                [["Opus 5", *[c5[k] for k in MENU], sum(c5.values())],
                 ["Opus 5.5 (R015)", *[c55[k] for k in MENU], sum(c55.values())]]), ""]

    RESULTS.write_text("\n".join(L), encoding="utf-8")
    print(RESULTS.read_text(encoding="utf-8"))


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    {"collect": collect, "analyze": analyze}.get(cmd, lambda: sys.exit(__doc__))()
