#!/usr/bin/env python3
"""Research-policy gate for the principia theory corpus.

Validates claim registries, gate cards, the refuted wall, postulate expiry,
essay-ledger coverage, link resolution, and that ledger.md matches the
generated rollup.

Usage:
    python3 scripts/check-theory.py              # check, including ledger freshness
    python3 scripts/check-theory.py --write-ledger
    python3 scripts/check-theory.py --selftest
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEORY = ROOT / "theory"
GATES = ROOT / "gates"
SCHEMA = ROOT / "schema"
LEDGER = ROOT / "ledger.md"
WALL = SCHEMA / "wall.json"

DOC_STATUSES = {"exploratory", "growing", "refuted", "resolved", "retired"}
CLAIM_STATUSES = {"supported", "mixed", "untested", "refuted", "conjecture"}
KINDS = {"postulate", "derived", "model-property", "nature", "hook"}
GATE_KINDS = {"existence", "control", "derivation", "phenomenology"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
MD_LINK_RE = re.compile(r"!?\[[^\]]*\][(]([^)]+)[)]")
LEDGER_START = "<!-- AUTO-LEDGER:start — generated by scripts/check-theory.py; do not edit below by hand -->"
LEDGER_END = "<!-- AUTO-LEDGER:end -->"
CANONICAL_H2 = {
    "evidence-ledger.md": "## Evidence ledger",
    "related.md": "## Related",
    "open-questions.md": "## Open questions",
}
FORBIDDEN_H2 = set(CANONICAL_H2.values()) | {"## Open debts", "## Where it feeds"}
HUB_FRONTMATTER_KEYS = ("title", "status", "families", "almanac", "created", "updated")
DIR_REQUIRED_FILES = ("README.md", "claims.json", "evidence-ledger.md", "related.md", "open-questions.md")


def fail(errors: list[str]) -> int:
    for item in errors:
        print(f"error: {item}", file=sys.stderr)
    print(f"{len(errors)} error(s)", file=sys.stderr)
    return 1


def parse_date(value: str, loc: str, errors: list[str]) -> dt.date | None:
    if not value or not DATE_RE.match(value):
        errors.append(f"{loc}: date must be YYYY-MM-DD, got {value!r}")
        return None
    return dt.date.fromisoformat(value)


def norm_status(raw: str) -> str:
    text = raw.strip().lower()
    for status in ("supported", "mixed", "untested", "refuted", "conjecture"):
        if text.startswith(status):
            return status
    return raw.strip()


def split_row(line: str) -> list[str]:
    cells = [c.strip() for c in re.split(r"(?<!\\)\|", line.strip())]
    if cells and cells[0] == "":
        cells = cells[1:]
    if cells and cells[-1] == "":
        cells = cells[:-1]
    return cells


def parse_essay_ledger(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    in_section = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip() == "## Evidence ledger":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if not in_section or not line.startswith("|"):
            continue
        cells = split_row(line)
        if not cells or cells[0] == "Claim" or cells[0].startswith("---"):
            continue
        if set(cells[0]) <= set("-: "):
            continue
        rows.append(
            {
                "claim": cells[0],
                "status": norm_status(cells[1] if len(cells) > 1 else ""),
            }
        )
    return rows


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def doc_layout_and_stem(path: Path) -> tuple[str, str]:
    if path.name == "claims.json":
        return "dir", path.parent.name
    return "flat", path.name.removesuffix(".claims.json")


def iter_claim_files(theory: Path) -> list[Path]:
    return sorted(theory.glob("*/claims.json"))


def iter_theories(theory: Path, errors: list[str]) -> list[tuple[str, str]]:
    """Return (stem, layout). Directory layout is the only pairing."""
    if not theory.is_dir():
        return []
    for path in sorted(theory.glob("*.md")):
        if path.name != "README.md":
            errors.append(f"theory/{path.name}: leftover flat essay; theories live in theory/<slug>/")
    for path in sorted(theory.glob("*.claims.json")):
        errors.append(f"theory/{path.name}: leftover flat registry; theories live in theory/<slug>/")
    stems: set[str] = set()
    for path in theory.glob("*/README.md"):
        stems.add(path.parent.name)
    for path in theory.glob("*/claims.json"):
        stems.add(path.parent.name)
    return [(stem, "dir") for stem in sorted(stems)]


def parse_hub_frontmatter(text: str, loc: str, errors: list[str]) -> dict[str, object]:
    """Parse a leading --- key: value --- block. families: [a, b] is the only structure."""
    if not text.startswith("---\n"):
        errors.append(f"{loc}: missing YAML frontmatter")
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        errors.append(f"{loc}: unterminated frontmatter")
        return {}
    data: dict[str, object] = {}
    for raw in text[4:end].splitlines():
        if not raw.strip() or raw.strip().startswith("#"):
            continue
        if ":" not in raw:
            errors.append(f"{loc}: bad frontmatter line {raw!r}")
            continue
        key, val = raw.split(":", 1)
        key, val = key.strip(), val.strip()
        if key == "families":
            inner = val.strip()
            if inner.startswith("[") and inner.endswith("]"):
                data[key] = [
                    x.strip().strip('"').strip("'")
                    for x in inner[1:-1].split(",")
                    if x.strip()
                ]
            else:
                errors.append(f"{loc}: families must be an inline list")
        else:
            data[key] = val.strip('"').strip("'")
    for key in HUB_FRONTMATTER_KEYS:
        if key not in data:
            errors.append(f"{loc}: missing {key}")
    return data


def load_corpus(root: Path) -> tuple[list[dict], list[dict], list[str], dict]:
    theory = root / "theory"
    gates_dir = root / "gates"
    errors: list[str] = []
    docs: list[dict] = []
    for path in iter_claim_files(theory):
        try:
            data = load_json(path)
        except json.JSONDecodeError as exc:
            errors.append(f"{path.relative_to(root)}: invalid JSON ({exc})")
            continue
        if not isinstance(data, dict):
            errors.append(f"{path.relative_to(root)}: document must be an object")
            continue
        data["_path"] = path
        layout, stem = doc_layout_and_stem(path)
        data["_layout"] = layout
        data["_stem"] = stem
        docs.append(data)
    gates: list[dict] = []
    if gates_dir.is_dir():
        for path in sorted(gates_dir.glob("*.json")):
            try:
                data = load_json(path)
            except json.JSONDecodeError as exc:
                errors.append(f"{path.relative_to(root)}: invalid JSON ({exc})")
                continue
            if not isinstance(data, dict):
                errors.append(f"{path.relative_to(root)}: gate must be an object")
                continue
            data["_path"] = path
            gates.append(data)
    wall: dict = {"refuted_ids": []}
    wall_path = root / "schema" / "wall.json"
    if wall_path.is_file():
        try:
            loaded = load_json(wall_path)
            if isinstance(loaded, dict):
                wall = loaded
            else:
                errors.append("schema/wall.json: must be an object")
        except json.JSONDecodeError as exc:
            errors.append(f"schema/wall.json: invalid JSON ({exc})")
    return docs, gates, errors, wall


def claim_index(docs: list[dict]) -> dict[str, dict]:
    by_id: dict[str, dict] = {}
    for doc in docs:
        for claim in doc.get("claims") or []:
            if isinstance(claim, dict) and claim.get("id"):
                by_id[claim["id"]] = claim
    return by_id


@dataclass(frozen=True)
class ExternalRoot:
    path: Path
    source: str


@dataclass(frozen=True)
class LinkResolution:
    path: Path | None
    error: str | None = None


def worktree_external_roots(root: Path) -> dict[str, ExternalRoot]:
    """Find supported sibling research checkouts from Git's common-dir metadata."""
    try:
        common_dir = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--git-common-dir"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return {}
    common_path = Path(common_dir)
    if not common_path.is_absolute():
        common_path = root / common_path
    # <constellation>/principia/.git is Git's common directory, so its
    # grandparent is the checkout collection containing sibling repositories.
    collection = common_path.resolve().parent.parent
    return {"orrery": ExternalRoot(collection / "orrery", "Git worktree metadata")}


def parse_external_roots(specs: list[str]) -> dict[str, ExternalRoot]:
    roots: dict[str, ExternalRoot] = {}
    for spec in specs:
        name, separator, raw_path = spec.partition("=")
        if not separator or not name or not raw_path or "/" in name or "\\" in name or name in {".", ".."}:
            raise ValueError(f"external root must be NAME=PATH with a simple NAME, got {spec!r}")
        roots[name] = ExternalRoot(Path(raw_path).expanduser().resolve(), "--external-root")
    return roots


def external_roots(root: Path, configured: dict[str, ExternalRoot] | None = None) -> dict[str, ExternalRoot]:
    """Return worktree roots overlaid by explicit mappings."""
    roots = worktree_external_roots(root)
    roots.update(configured or {})
    return roots


def resolve_link(
    link: str,
    from_dir: Path,
    root: Path,
    configured_external_roots: dict[str, ExternalRoot] | None = None,
) -> LinkResolution | None:
    if link.startswith(("http://", "https://", "mailto:")):
        return None
    path_part = link.split("#", 1)[0]
    if not path_part:
        return None
    raw_path = Path(path_part)
    if raw_path.is_absolute():
        return LinkResolution(None, "absolute filesystem links are not allowed")
    try:
        within_root = list(from_dir.relative_to(root).parts)
    except ValueError:
        return LinkResolution(None, f"link source is outside candidate root {root}")
    escaped = 0
    repository: str | None = None
    external_parts: list[str] = []
    for part in raw_path.parts:
        if part in {"", "."}:
            continue
        if part == "..":
            if repository is not None:
                if not external_parts:
                    return LinkResolution(None, "external link escapes its configured repository root")
                external_parts.pop()
            elif within_root:
                within_root.pop()
            else:
                escaped += 1
            continue
        if escaped:
            if repository is None:
                if escaped != 1:
                    return LinkResolution(
                        None, f"link escapes candidate root by {escaped} levels before its repository name"
                    )
                repository = part
            else:
                external_parts.append(part)
        else:
            within_root.append(part)
    if repository is None:
        if escaped:
            return LinkResolution(None, "link escapes candidate root without a repository name")
        return LinkResolution(root.joinpath(*within_root))

    roots = (
        configured_external_roots
        if configured_external_roots is not None
        else external_roots(root)
    )
    mapped_root = roots.get(repository)
    if mapped_root is None:
        return LinkResolution(None, f"external repository {repository!r} is not configured")
    target = mapped_root.path.joinpath(*external_parts)
    if not mapped_root.path.is_dir():
        return LinkResolution(
            target,
            f"external checkout {repository!r} is unavailable at {mapped_root.path} ({mapped_root.source})",
        )
    return LinkResolution(target)


def heading_lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.startswith("## ")
    ]


def check_dir_layout(root: Path, stem: str, doc: dict, errors: list[str]) -> None:
    theory = root / "theory"
    loc = f"theory/{stem}"
    hub = theory / stem / "README.md"
    if hub.is_file():
        yaml = parse_hub_frontmatter(hub.read_text(encoding="utf-8"), f"{loc}/README.md", errors)
        if yaml.get("status") not in DOC_STATUSES and "status" in yaml:
            errors.append(f"{loc}/README.md: invalid doc status {yaml.get('status')!r}")
        if yaml.get("title") != doc.get("title"):
            errors.append(
                f"{loc}/README.md: title {yaml.get('title')!r} != registry {doc.get('title')!r}"
            )
        if yaml.get("status") != doc.get("status"):
            errors.append(
                f"{loc}/README.md: status {yaml.get('status')!r} != registry {doc.get('status')!r}"
            )
        if yaml.get("families") != doc.get("families"):
            errors.append(
                f"{loc}/README.md: families {yaml.get('families')!r} != registry {doc.get('families')!r}"
            )
        text = hub.read_text(encoding="utf-8")
        if "## Contents" not in text:
            errors.append(f"{loc}/README.md: missing ## Contents")
        else:
            for name in ("evidence-ledger.md", "related.md", "open-questions.md"):
                if name not in text:
                    errors.append(f"{loc}/README.md: ## Contents must link {name}")
    for md in sorted((theory / stem).glob("*.md")):
        h2s = heading_lines(md)
        rel = md.relative_to(root).as_posix()
        if md.name in CANONICAL_H2:
            allowed = CANONICAL_H2[md.name]
            if allowed not in h2s:
                errors.append(f"{rel}: missing {allowed}")
            for heading in h2s:
                if heading != allowed:
                    errors.append(
                        f"{rel}: extra H2 {heading!r}; this file may only have {allowed}"
                    )
        else:
            for heading in h2s:
                if heading in FORBIDDEN_H2:
                    errors.append(
                        f"{rel}: heading {heading!r} belongs in the canonical file"
                    )


def check_markdown_links(
    root: Path, configured_external_roots: dict[str, ExternalRoot] | None = None
) -> list[str]:
    errors: list[str] = []
    files: list[Path] = []
    theory = root / "theory"
    if theory.is_dir():
        for path in sorted(theory.glob("*.md")):
            if path.name != "README.md":
                files.append(path)
        files.extend(sorted(theory.glob("*/*.md")))
    studies = root / "studies"
    if studies.is_dir():
        files.extend(sorted(studies.glob("*.md")))
    for path in files:
        try:
            rel = path.relative_to(root).as_posix()
        except ValueError:
            rel = str(path)
        for match in MD_LINK_RE.finditer(path.read_text(encoding="utf-8")):
            url = match.group(1).strip()
            if url.startswith(("<", "{")):
                continue
            resolution = resolve_link(url, path.parent, root, configured_external_roots)
            if resolution is None:
                continue
            if resolution.error:
                errors.append(f"{rel}: {resolution.error}: {url}")
            elif resolution.path is None or not resolution.path.exists():
                errors.append(f"{rel}: link does not resolve: {url} (resolved to {resolution.path})")
    return errors


def check_docs(
    root: Path,
    docs: list[dict],
    today: dt.date,
    configured_external_roots: dict[str, ExternalRoot] | None = None,
) -> list[str]:
    errors: list[str] = []
    theory = root / "theory"
    for stem, layout in iter_theories(theory, errors):
        if layout == "flat":
            essay = theory / f"{stem}.md"
            claims_path = theory / f"{stem}.claims.json"
            if essay.is_file() and not claims_path.is_file():
                errors.append(f"theory/{stem}.md: missing theory/{stem}.claims.json")
            if claims_path.is_file() and not essay.is_file():
                errors.append(f"theory/{stem}.claims.json: no matching theory/{stem}.md")
        else:
            for name in DIR_REQUIRED_FILES:
                if not (theory / stem / name).is_file():
                    errors.append(f"theory/{stem}/{name}: missing")
            extra_json = [
                p.name for p in sorted((theory / stem).glob("*.json")) if p.name != "claims.json"
            ]
            for name in extra_json:
                errors.append(f"theory/{stem}/{name}: extra JSON; only claims.json is allowed")

    seen_ids: dict[str, str] = {}
    for doc in docs:
        loc = doc["_path"].relative_to(root).as_posix()
        layout = doc.get("_layout") or doc_layout_and_stem(doc["_path"])[0]
        stem = doc.get("_stem") or doc_layout_and_stem(doc["_path"])[1]
        for key in ("doc", "title", "status", "families", "updated", "headline", "live_fronts", "claims"):
            if key not in doc:
                errors.append(f"{loc}: missing {key}")
        if doc.get("doc") != stem:
            kind = "directory name" if layout == "dir" else "filename stem"
            errors.append(f"{loc}: doc {doc.get('doc')!r} must equal {kind} {stem!r}")
        if doc.get("status") not in DOC_STATUSES:
            errors.append(f"{loc}: invalid doc status {doc.get('status')!r}")
        families = doc.get("families")
        if not isinstance(families, list) or not families or not all(isinstance(x, str) and x for x in families):
            errors.append(f"{loc}: families must be a nonempty list of strings")
            families = []
        live = doc.get("live_fronts")
        if not isinstance(live, list) or not all(isinstance(x, str) for x in live):
            errors.append(f"{loc}: live_fronts must be a list of strings")
            live = []
        if doc.get("status") in {"growing", "exploratory"} and not live:
            errors.append(f"{loc}: growing/exploratory docs need a live_fronts gate id")
        if doc.get("status") in {"refuted", "resolved", "retired"} and live:
            errors.append(f"{loc}: refuted/resolved/retired docs must have empty live_fronts")
        parse_date(str(doc.get("updated") or ""), f"{loc}.updated", errors)
        claims = doc.get("claims")
        if not isinstance(claims, list):
            errors.append(f"{loc}: claims must be a list")
            continue
        for i, claim in enumerate(claims):
            cloc = f"{loc} claims[{i}]"
            if not isinstance(claim, dict):
                errors.append(f"{cloc}: must be an object")
                continue
            cid = claim.get("id")
            if not isinstance(cid, str) or not cid:
                errors.append(f"{cloc}: missing id")
                continue
            if cid in seen_ids:
                errors.append(f"{cloc}: duplicate id {cid!r} (also {seen_ids[cid]})")
            seen_ids[cid] = cloc
            if claim.get("family") not in families:
                errors.append(f"{cloc} ({cid}): family {claim.get('family')!r} not in doc families {families}")
            if claim.get("kind") not in KINDS:
                errors.append(f"{cloc} ({cid}): invalid kind {claim.get('kind')!r}")
            if claim.get("status") not in CLAIM_STATUSES:
                errors.append(f"{cloc} ({cid}): invalid status {claim.get('status')!r}")
            if not isinstance(claim.get("claim"), str) or not claim["claim"].strip():
                errors.append(f"{cloc} ({cid}): missing claim text")
            if not isinstance(claim.get("in_doc_ledger"), bool):
                errors.append(f"{cloc} ({cid}): in_doc_ledger must be a boolean")
            tags = claim.get("tags") or []
            if not isinstance(tags, list) or not all(isinstance(t, str) for t in tags):
                errors.append(f"{cloc} ({cid}): tags must be a list of strings")
                tags = []
            links = claim.get("links") or []
            if not isinstance(links, list) or not all(isinstance(x, str) for x in links):
                errors.append(f"{cloc} ({cid}): links must be a list of strings")
                links = []
            # from_dir is the claims file's parent: theory/ when flat, theory/<slug>/ when dir.
            from_dir = doc["_path"].parent
            for link in links:
                resolution = resolve_link(link, from_dir, root, configured_external_roots)
                if resolution is None:
                    continue
                if resolution.error:
                    errors.append(f"{cloc} ({cid}): {resolution.error}: {link}")
                elif resolution.path is None or not resolution.path.exists():
                    errors.append(
                        f"{cloc} ({cid}): link does not resolve: {link} "
                        f"(resolved to {resolution.path})"
                    )
            if claim.get("kind") == "postulate":
                if claim.get("status") == "supported":
                    errors.append(
                        f"{cloc} ({cid}): a postulate cannot be supported; "
                        "lattice theorems of a named law are kind model-property"
                    )
                if not claim.get("named"):
                    errors.append(f"{cloc} ({cid}): postulate needs named: YYYY-MM-DD")
                else:
                    parse_date(str(claim["named"]), f"{cloc} ({cid}).named", errors)
                if claim.get("derived") is True:
                    pass
                else:
                    expires = claim.get("expires")
                    if not expires:
                        errors.append(f"{cloc} ({cid}): underived postulate needs expires")
                    else:
                        exp = parse_date(str(expires), f"{cloc} ({cid}).expires", errors)
                        if exp is not None and exp < today and doc.get("status") != "retired":
                            errors.append(
                                f"{cloc} ({cid}): postulate expired {expires}; "
                                "renew with a reason or derive it"
                            )
                    if not (claim.get("kill") or "").strip():
                        errors.append(f"{cloc} ({cid}): underived postulate needs kill")
            if claim.get("kind") == "hook":
                if not (claim.get("control") or "").strip():
                    errors.append(f"{cloc} ({cid}): hook needs control (the coupling-off run)")
                if claim.get("status") == "supported" and not claim.get("control_ran"):
                    errors.append(
                        f"{cloc} ({cid}): hook cannot be supported until control_ran is true"
                    )
            if claim.get("status") == "untested" and not (claim.get("kill") or "").strip():
                errors.append(f"{cloc} ({cid}): untested claim needs kill")
            if "preferred-frame" in tags and not (claim.get("comparator") or "").strip():
                errors.append(f"{cloc} ({cid}): preferred-frame tag requires comparator")
            if "phenomenology" in tags and claim.get("status") in {"untested", "mixed", "supported"}:
                blocked = claim.get("blocked_by") or []
                if not blocked:
                    errors.append(
                        f"{cloc} ({cid}): live phenomenology must name blocked_by existence claims"
                    )
            blocked = claim.get("blocked_by") or []
            reopens = claim.get("reopens") or []
            if not isinstance(blocked, list) or not isinstance(reopens, list):
                errors.append(f"{cloc} ({cid}): blocked_by and reopens must be lists")
            if reopens and not claim.get("daniel_reopen"):
                errors.append(
                    f"{cloc} ({cid}): reopens {reopens} requires daniel_reopen: true"
                )

        if layout == "dir":
            ledger_md = theory / stem / "evidence-ledger.md"
            table = parse_essay_ledger(ledger_md) if ledger_md.is_file() else []
            if not ledger_md.is_file():
                errors.append(f"theory/{stem}/evidence-ledger.md: missing")
            check_dir_layout(root, stem, doc, errors)
        else:
            essay = theory / f"{stem}.md"
            table = parse_essay_ledger(essay) if essay.is_file() else []
        ledger_claims = [
            c for c in claims if isinstance(c, dict) and c.get("in_doc_ledger") is True
        ]
        table_by_claim = {r["claim"]: r for r in table}
        json_by_claim = {c.get("claim"): c for c in ledger_claims}
        for row in table:
            match = json_by_claim.get(row["claim"])
            if match is None:
                errors.append(
                    f"{loc}: essay ledger row not in registry: {row['claim'][:80]}"
                )
            elif match.get("status") != row["status"]:
                errors.append(
                    f"{loc}: status mismatch for {match.get('id')}: "
                    f"registry {match.get('status')} vs essay {row['status']}"
                )
        for claim in ledger_claims:
            if claim.get("claim") not in table_by_claim:
                errors.append(
                    f"{loc}: registry claim {claim.get('id')} missing from essay ledger"
                )
    return errors


def check_cross(docs: list[dict], gates: list[dict], wall: dict, root: Path) -> list[str]:
    errors: list[str] = []
    by_id = claim_index(docs)
    gate_ids = {}
    for gate in gates:
        loc = gate["_path"].relative_to(root).as_posix()
        gid = gate.get("id")
        if not isinstance(gid, str) or not gid:
            errors.append(f"{loc}: missing id")
            continue
        if gid in gate_ids:
            errors.append(f"{loc}: duplicate gate id {gid}")
        gate_ids[gid] = gate
        for key in (
            "doc",
            "family",
            "kind",
            "owed_object",
            "inherited_postulates",
            "new_postulates",
            "control",
            "kill",
            "forbidden_reopens",
            "comparator",
        ):
            if key not in gate:
                errors.append(f"{loc}: missing {key}")
        if gate.get("kind") not in GATE_KINDS:
            errors.append(f"{loc}: invalid kind {gate.get('kind')!r}")
        if not (gate.get("owed_object") or "").strip():
            errors.append(f"{loc}: owed_object is empty")
        if not (gate.get("kill") or "").strip():
            errors.append(f"{loc}: kill is empty")
        if not (gate.get("control") or "").strip():
            errors.append(f"{loc}: control is empty")
        if not (gate.get("comparator") or "").strip():
            errors.append(f"{loc}: comparator is empty")
        if gate.get("kind") == "phenomenology":
            errors.append(
                f"{loc}: phenomenology gates are not yet allowed; "
                "existence must pass first (file a notebook estimate, not a lattice card)"
            )
        doc_stems = {d.get("doc") for d in docs}
        if gate.get("doc") not in doc_stems:
            errors.append(f"{loc}: doc {gate.get('doc')!r} is not a known theory doc")
        family_ok = any(gate.get("family") in (d.get("families") or []) for d in docs)
        if not family_ok:
            errors.append(f"{loc}: family {gate.get('family')!r} is not a known family")
        for pid in gate.get("inherited_postulates") or []:
            target = by_id.get(pid)
            if target is None:
                errors.append(f"{loc}: inherited postulate {pid} not in registry")
            elif target.get("kind") != "postulate":
                errors.append(f"{loc}: inherited {pid} is kind {target.get('kind')}, not postulate")
        for pid in gate.get("new_postulates") or []:
            target = by_id.get(pid)
            if target is None:
                errors.append(f"{loc}: new postulate {pid} not in registry")
            elif target.get("kind") != "postulate":
                errors.append(f"{loc}: new_postulates {pid} is not a postulate")
            elif not target.get("expires"):
                errors.append(f"{loc}: new postulate {pid} needs expires")
        for rid in gate.get("forbidden_reopens") or []:
            if rid not in by_id:
                errors.append(f"{loc}: forbidden_reopens {rid} not in registry")
        for cid in gate.get("claims") or []:
            if cid not in by_id:
                errors.append(f"{loc}: claims {cid} not in registry")

    family_fronts: dict[str, set[str]] = {}
    for doc in docs:
        loc = doc["_path"].relative_to(root).as_posix()
        for gid in doc.get("live_fronts") or []:
            if gid not in gate_ids:
                errors.append(f"{loc}: live_fronts {gid} is not a gate")
                continue
            gate = gate_ids[gid]
            for fam in doc.get("families") or []:
                family_fronts.setdefault(fam, set()).add(gid)
            if gate.get("family") not in (doc.get("families") or []):
                errors.append(
                    f"{loc}: live front {gid} is family {gate.get('family')}, "
                    f"doc families are {doc.get('families')}"
                )
    for fam, fronts in sorted(family_fronts.items()):
        if len(fronts) > 1:
            errors.append(
                f"family {fam}: multiple live fronts {sorted(fronts)}; one live front per family"
            )

    for doc in docs:
        for claim in doc.get("claims") or []:
            if not isinstance(claim, dict):
                continue
            cid = claim.get("id")
            loc = f"{doc['_path'].relative_to(root).as_posix()} ({cid})"
            for bid in claim.get("blocked_by") or []:
                if bid not in by_id:
                    errors.append(f"{loc}: blocked_by {bid} not in registry")
                    continue
                if "phenomenology" in (claim.get("tags") or []) and claim.get("status") in {
                    "untested",
                    "mixed",
                    "supported",
                }:
                    if by_id[bid].get("status") != "supported":
                        errors.append(
                            f"{loc}: phenomenology blocked by {bid} "
                            f"(status {by_id[bid].get('status')}, need supported)"
                        )
            debt = claim.get("pays_debt_of")
            if debt:
                if debt not in by_id:
                    errors.append(f"{loc}: pays_debt_of {debt} not in registry")
                elif by_id[debt].get("family") != claim.get("family"):
                    errors.append(
                        f"{loc}: pays_debt_of {debt} is family "
                        f"{by_id[debt].get('family')}; family A cannot pay family B"
                    )
            for rid in claim.get("reopens") or []:
                if rid not in by_id:
                    errors.append(f"{loc}: reopens {rid} not in registry")
                elif by_id[rid].get("status") != "refuted" and not claim.get("daniel_reopen"):
                    errors.append(f"{loc}: reopens {rid} is not refuted")

    hooks_needing_control = [
        c["id"]
        for d in docs
        for c in d.get("claims") or []
        if isinstance(c, dict)
        and c.get("kind") == "hook"
        and not c.get("control_ran")
        and c.get("id")
    ]
    for hid in hooks_needing_control:
        control_gates = [
            g
            for g in gates
            if g.get("kind") == "control" and hid in (g.get("claims") or [])
        ]
        if not control_gates:
            errors.append(
                f"hook {hid}: control has not run; needs a kind:control gate citing this claim"
            )

    wall_ids = wall.get("refuted_ids") or []
    if not isinstance(wall_ids, list):
        errors.append("schema/wall.json: refuted_ids must be a list")
        wall_ids = []
    for wid in wall_ids:
        if wid not in by_id:
            errors.append(f"schema/wall.json: wall id {wid} missing from registry")
            continue
        target = by_id[wid]
        if target.get("status") != "refuted" and not target.get("daniel_reopen"):
            errors.append(
                f"schema/wall.json: {wid} is status {target.get('status')}, not refuted"
            )
    return errors


def render_ledger(docs: list[dict], gates: list[dict], wall: dict) -> str:
    by_status: dict[str, list[tuple[str, dict]]] = {s: [] for s in CLAIM_STATUSES}
    for doc in docs:
        fam = (doc.get("families") or ["?"])[0]
        for claim in doc.get("claims") or []:
            if not isinstance(claim, dict):
                continue
            status = claim.get("status")
            if status in by_status:
                by_status[status].append((fam, claim))

    lines: list[str] = []
    lines.append("---")
    lines.append('title: "Master ledger — every theory claim, grouped by verdict"')
    lines.append("status: generated")
    lines.append("---")
    lines.append("")
    lines.append("# Master ledger")
    lines.append("")
    lines.append(
        "One-page rollup of every claim in the `theory/` registries, regrouped **by verdict**"
    )
    lines.append(
        "instead of by document. The **source of truth is `theory/<doc>/claims.json`**, not"
    )
    lines.append(
        "this file and not the essay tables (the tables must match the registry)."
    )
    lines.append(
        "Regenerate with `python3 scripts/check-theory.py --write-ledger`."
    )
    lines.append("")
    lines.append(LEDGER_START)
    lines.append("")
    lines.append("## Theory families at a glance")
    lines.append("")
    def cell(text: object, limit: int | None = None) -> str:
        value = str(text or "").replace("\n", " ").replace("|", "\\|")
        if limit is not None and len(value) > limit:
            value = value[: limit - 3] + "…"
        return value

    lines.append("| Doc | Doc status | Headline verdict |")
    lines.append("|---|---|---|")
    for doc in sorted(docs, key=lambda d: d.get("doc") or ""):
        slug = doc.get("doc")
        href = f"theory/{slug}/" if doc.get("_layout") == "dir" else f"theory/{slug}.md"
        lines.append(
            f"| [{slug}]({href}) | {doc.get('status')} | {cell(doc.get('headline'))} |"
        )
    lines.append("")

    sections = [
        (
            "Refuted",
            "Evidence kills the claim as stated. Full obituaries in the source rows.",
            "refuted",
            "Killed by",
        ),
        (
            "Mixed",
            "Evidence cuts both ways — the source row says exactly how.",
            "mixed",
            "State of the evidence",
        ),
        (
            "Supported",
            "A cataloged sim or sourced study backs the row — model-properties are true of the *model*, not of nature.",
            "supported",
            "Evidence",
        ),
        (
            "Untested",
            "Stated but not yet simulated or cataloged.",
            "untested",
            "What it waits on",
        ),
        (
            "Conjecture",
            "Not yet backed by anything; `to verify` rows await a sourced study note.",
            "conjecture",
            "Note",
        ),
    ]
    for title, blurb, status, third in sections:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        lines.append(f"| Family | Id | Claim | {third} |")
        lines.append("|---|---|---|---|")
        rows = sorted(by_status[status], key=lambda item: (item[0], item[1].get("id") or ""))
        if not rows:
            lines.append("| — | — | — | — |")
        for fam, claim in rows:
            text = cell(claim.get("claim"), 180)
            extra = claim.get("kill") if status == "untested" else (claim.get("evidence") or "")
            extra = cell(extra, 220)
            lines.append(f"| {fam} | `{claim.get('id')}` | {text} | {extra} |")
        lines.append("")

    lines.append("## Live fronts")
    lines.append("")
    lines.append("| Gate | Kind | Family | Owed object | Kill |")
    lines.append("|---|---|---|---|---|")
    for gate in sorted(gates, key=lambda g: g.get("id") or ""):
        lines.append(
            f"| `{gate.get('id')}` | {gate.get('kind')} | {gate.get('family')} | "
            f"{cell(gate.get('owed_object'))} | {cell(gate.get('kill'))} |"
        )
    lines.append("")
    lines.append("## Refuted wall")
    lines.append("")
    wall_ids = wall.get("refuted_ids") or []
    lines.append(", ".join(f"`{i}`" for i in wall_ids) if wall_ids else "—")
    lines.append("")
    lines.append(LEDGER_END)
    lines.append("")
    return "\n".join(lines)


def check_ledger(root: Path, expected: str) -> list[str]:
    path = root / "ledger.md"
    if not path.is_file():
        return ["ledger.md is missing; run python3 scripts/check-theory.py --write-ledger"]
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return ["ledger.md is stale; run python3 scripts/check-theory.py --write-ledger"]
    return []


def run_checks(
    root: Path,
    today: dt.date | None = None,
    configured_external_roots: dict[str, ExternalRoot] | None = None,
) -> tuple[list[str], str, list[dict], list[dict], dict]:
    today = today or dt.date.today()
    docs, gates, errors, wall = load_corpus(root)
    resolved_external_roots = external_roots(root, configured_external_roots)
    errors.extend(check_docs(root, docs, today, resolved_external_roots))
    errors.extend(check_cross(docs, gates, wall, root))
    errors.extend(check_markdown_links(root, resolved_external_roots))
    expected = render_ledger(docs, gates, wall)
    return errors, expected, docs, gates, wall


def write_fixture_claim(
    directory: Path,
    stem: str,
    layout: str = "dir",
    **overrides: object,
) -> None:
    doc = {
        "doc": stem,
        "title": stem,
        "status": "growing",
        "families": ["demo-family"],
        "updated": "2026-08-21",
        "headline": "demo",
        "live_fronts": ["demo-front"],
        "claims": [
            {
                "id": "demo-postulate",
                "family": "demo-family",
                "kind": "postulate",
                "status": "mixed",
                "claim": "A named rule.",
                "evidence": "",
                "links": [],
                "in_doc_ledger": True,
                "tags": [],
                "kill": "it fails",
                "named": "2026-08-21",
                "expires": "2026-09-21",
                "derived": False,
            }
        ],
    }
    doc.update(overrides)
    payload = {k: v for k, v in doc.items() if not str(k).startswith("_")}
    ledger = (
        "## Evidence ledger\n\n"
        "| Claim | Status | Evidence |\n|---|---|---|\n"
        "| A named rule. | mixed | n |\n"
    )
    if layout == "dir":
        target = directory / "theory" / stem
        target.mkdir(parents=True, exist_ok=True)
        (target / "claims.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        families = payload.get("families") or ["demo-family"]
        fam_list = ", ".join(str(x) for x in families)
        title = payload.get("title") or stem
        status = payload.get("status") or "growing"
        updated = payload.get("updated") or "2026-08-21"
        (target / "README.md").write_text(
            f"---\n"
            f'title: "{title}"\n'
            f"status: {status}\n"
            f"families: [{fam_list}]\n"
            f"almanac: none\n"
            f"created: 2026-08-21\n"
            f"updated: {updated}\n"
            f"---\n\n"
            f"# {title}\n\n"
            f"## Contents\n\n"
            f"- [Evidence ledger](evidence-ledger.md)\n"
            f"- [Related](related.md)\n"
            f"- [Open questions](open-questions.md)\n",
            encoding="utf-8",
        )
        (target / "evidence-ledger.md").write_text(ledger, encoding="utf-8")
        (target / "related.md").write_text("## Related\n\nNone currently.\n", encoding="utf-8")
        (target / "open-questions.md").write_text(
            "## Open questions\n\nNone currently.\n", encoding="utf-8"
        )
        return
    (directory / "theory" / f"{stem}.claims.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )
    (directory / "theory" / f"{stem}.md").write_text(
        f"# demo\n\n{ledger}",
        encoding="utf-8",
    )


def write_fixture_gate(directory: Path, stem: str = "demo") -> None:
    (directory / "gates" / f"{stem}-front.json").write_text(
        json.dumps(
            {
                "id": f"{stem}-front",
                "doc": stem,
                "family": "demo-family",
                "kind": "existence",
                "owed_object": "does it exist",
                "inherited_postulates": ["demo-postulate"],
                "new_postulates": [],
                "control": "off",
                "kill": "no",
                "forbidden_reopens": [],
                "comparator": "none",
                "claims": ["demo-postulate"],
            }
        )
        + "\n",
        encoding="utf-8",
    )


def selftest() -> int:
    failures: list[str] = []

    def expect_error(label: str, root: Path, needle: str, today: dt.date | None = None) -> None:
        errors, _, _, _, _ = run_checks(root, today=today)
        blob = "\n".join(errors)
        if needle not in blob:
            failures.append(f"{label}: expected {needle!r} in errors, got:\n{blob}")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "theory").mkdir()
        (root / "gates").mkdir()
        (root / "schema").mkdir()
        write_fixture_claim(root, "demo")
        (root / "schema" / "wall.json").write_text(
            json.dumps({"refuted_ids": []}) + "\n", encoding="utf-8"
        )
        (root / "gates" / "demo-front.json").write_text(
            json.dumps(
                {
                    "id": "demo-front",
                    "doc": "demo",
                    "family": "demo-family",
                    "kind": "existence",
                    "owed_object": "does it exist",
                    "inherited_postulates": ["demo-postulate"],
                    "new_postulates": [],
                    "control": "off",
                    "kill": "no",
                    "forbidden_reopens": [],
                    "comparator": "none",
                    "claims": ["demo-postulate"],
                }
            )
            + "\n",
            encoding="utf-8",
        )

        # Retirement archives debts without changing their evidence status. Resuming
        # research must reactivate expiry checks; retired docs cannot own live fronts.
        write_fixture_claim(root, "demo", status="retired", live_fronts=[])
        retirement_errors, _, _, _, _ = run_checks(root, today=dt.date(2026, 10, 1))
        if retirement_errors:
            failures.append(f"retired archive: {retirement_errors}")
        write_fixture_claim(root, "demo", status="retired")
        expect_error("retired-live-front", root, "must have empty live_fronts")
        write_fixture_claim(root, "demo")
        expect_error("resumed-expiry", root, "postulate expired", dt.date(2026, 10, 1))

        # postulate marked supported
        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-postulate",
                    "family": "demo-family",
                    "kind": "postulate",
                    "status": "supported",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "kill": "it fails",
                    "named": "2026-08-21",
                    "expires": "2026-09-21",
                    "derived": False,
                }
            ],
        )
        expect_error("postulate-supported", root, "a postulate cannot be supported")

        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-hook",
                    "family": "demo-family",
                    "kind": "hook",
                    "status": "supported",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "control_ran": False,
                }
            ],
        )
        expect_error("hook-no-control", root, "hook needs control")
        expect_error("hook-supported", root, "hook cannot be supported")

        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-postulate",
                    "family": "demo-family",
                    "kind": "postulate",
                    "status": "mixed",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "kill": "it fails",
                    "named": "2026-08-01",
                    "expires": "2026-08-10",
                    "derived": False,
                }
            ],
        )
        expect_error(
            "expired",
            root,
            "postulate expired",
            today=dt.date(2026, 8, 21),
        )

        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-pheno",
                    "family": "demo-family",
                    "kind": "nature",
                    "status": "untested",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "tags": ["phenomenology"],
                    "kill": "data",
                    "blocked_by": [],
                }
            ],
        )
        expect_error("pheno-blocked", root, "live phenomenology must name blocked_by")

        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-pf",
                    "family": "demo-family",
                    "kind": "nature",
                    "status": "mixed",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "tags": ["preferred-frame"],
                }
            ],
        )
        expect_error("comparator", root, "preferred-frame tag requires comparator")

        write_fixture_claim(
            root,
            "demo",
            claims=[
                {
                    "id": "demo-postulate",
                    "family": "demo-family",
                    "kind": "postulate",
                    "status": "mixed",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": [],
                    "in_doc_ledger": True,
                    "kill": "it fails",
                    "named": "2026-08-21",
                    "expires": "2026-09-21",
                    "derived": False,
                    "pays_debt_of": "missing-debt",
                }
            ],
        )
        expect_error("cross-debt", root, "pays_debt_of missing-debt not in registry")

        (root / "schema" / "wall.json").write_text(
            json.dumps({"refuted_ids": ["ghost-wall"]}) + "\n", encoding="utf-8"
        )
        expect_error("wall-missing", root, "wall id ghost-wall missing")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "theory").mkdir()
        (root / "gates").mkdir()
        (root / "schema").mkdir()
        (root / "studies").mkdir()
        (root / "studies" / "x.md").write_text("# x\n", encoding="utf-8")
        write_fixture_claim(root, "demo", layout="dir")
        (root / "schema" / "wall.json").write_text(
            json.dumps({"refuted_ids": []}) + "\n", encoding="utf-8"
        )
        (root / "gates" / "demo-front.json").write_text(
            json.dumps(
                {
                    "id": "demo-front",
                    "doc": "demo",
                    "family": "demo-family",
                    "kind": "existence",
                    "owed_object": "does it exist",
                    "inherited_postulates": ["demo-postulate"],
                    "new_postulates": [],
                    "control": "off",
                    "kill": "no",
                    "forbidden_reopens": [],
                    "comparator": "none",
                    "claims": ["demo-postulate"],
                }
            )
            + "\n",
            encoding="utf-8",
        )
        errors, _, _, _, _ = run_checks(root)
        if errors:
            failures.append(f"dir-layout-ok: unexpected errors:\n" + "\n".join(errors))

        hub = root / "theory" / "demo" / "README.md"
        hub.write_text(
            hub.read_text(encoding="utf-8") + "\nSee [near](../studies/x.md) and [far](../../studies/x.md).\n",
            encoding="utf-8",
        )
        errors, _, _, _, _ = run_checks(root)
        blob = "\n".join(errors)
        if "link does not resolve: ../studies/x.md" not in blob:
            failures.append(f"extra-parent-fail: expected ../studies miss, got:\n{blob}")
        if "link does not resolve: ../../studies/x.md" in blob:
            failures.append(f"extra-parent-pass: ../../studies should resolve, got:\n{blob}")

        (root / "theory" / "demo" / "evidence-ledger.md").write_text(
            "## Evidence ledger\n\n"
            "| Claim | Status | Evidence |\n|---|---|---|\n"
            "| A named rule. | mixed | n |\n\n"
            "## Notes\n\nno\n",
            encoding="utf-8",
        )
        expect_error("canonical-extra-h2", root, "extra H2 '## Notes'")

        write_fixture_claim(root, "demo", layout="flat")
        expect_error("leftover-flat", root, "leftover flat")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "theory").mkdir()
        (root / "gates").mkdir()
        (root / "schema").mkdir()
        sim = root / "lab" / "sims" / "bare-sim"
        sim.mkdir(parents=True)
        (sim / "sim.json").write_text("{}\n", encoding="utf-8")
        write_fixture_claim(
            root,
            "demo",
            layout="dir",
            claims=[
                {
                    "id": "demo-postulate",
                    "family": "demo-family",
                    "kind": "postulate",
                    "status": "mixed",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": ["../../lab/sims/bare-sim/"],
                    "in_doc_ledger": True,
                    "tags": [],
                    "kill": "it fails",
                    "named": "2026-08-21",
                    "expires": "2026-09-21",
                    "derived": False,
                }
            ],
        )
        (root / "schema" / "wall.json").write_text(
            json.dumps({"refuted_ids": []}) + "\n", encoding="utf-8"
        )
        (root / "gates" / "demo-front.json").write_text(
            json.dumps(
                {
                    "id": "demo-front",
                    "doc": "demo",
                    "family": "demo-family",
                    "kind": "existence",
                    "owed_object": "does it exist",
                    "inherited_postulates": ["demo-postulate"],
                    "new_postulates": [],
                    "control": "off",
                    "kill": "no",
                    "forbidden_reopens": [],
                    "comparator": "none",
                    "claims": ["demo-postulate"],
                }
            )
            + "\n",
            encoding="utf-8",
        )
        errors, _, _, _, _ = run_checks(root)
        if any("bare-sim" in e for e in errors):
            failures.append(
                "sim-dir-without-readme: directory target without README should pass, got:\n"
                + "\n".join(errors)
            )

    with tempfile.TemporaryDirectory() as tmp:
        collection = Path(tmp)
        primary = collection / "principia"
        external = collection / "orrery"
        primary.mkdir()
        for name in ("theory", "gates", "schema"):
            (primary / name).mkdir()
        sim = external / "lab" / "sims" / "bare-sim"
        sim.mkdir(parents=True)
        (sim / "sim.json").write_text("{}\n", encoding="utf-8")
        write_fixture_claim(
            primary,
            "demo",
            claims=[
                {
                    "id": "demo-postulate",
                    "family": "demo-family",
                    "kind": "postulate",
                    "status": "mixed",
                    "claim": "A named rule.",
                    "evidence": "",
                    "links": ["../../../orrery/lab/sims/bare-sim/"],
                    "in_doc_ledger": True,
                    "tags": [],
                    "kill": "it fails",
                    "named": "2026-08-21",
                    "expires": "2026-09-21",
                    "derived": False,
                }
            ],
        )
        (primary / "schema" / "wall.json").write_text(
            json.dumps({"refuted_ids": []}) + "\n", encoding="utf-8"
        )
        write_fixture_gate(primary)
        for command in (
            ["git", "-C", str(primary), "init", "-q"],
            ["git", "-C", str(primary), "config", "user.email", "selftest@example.invalid"],
            ["git", "-C", str(primary), "config", "user.name", "selftest"],
            ["git", "-C", str(primary), "add", "."],
            ["git", "-C", str(primary), "commit", "-qm", "fixture"],
        ):
            subprocess.run(command, check=True, capture_output=True, text=True)
        isolated = collection / "isolated"
        subprocess.run(
            ["git", "-C", str(primary), "worktree", "add", "-q", str(isolated), "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
        errors, _, _, _, _ = run_checks(primary)
        if errors:
            failures.append("primary-external-pass: unexpected errors:\n" + "\n".join(errors))
        errors, _, _, _, _ = run_checks(isolated)
        if errors:
            failures.append("worktree-external-pass: unexpected errors:\n" + "\n".join(errors))

        override = collection / "override-orrery"
        override_sim = override / "lab" / "sims" / "bare-sim"
        override_sim.mkdir(parents=True)
        (override_sim / "sim.json").write_text("{}\n", encoding="utf-8")
        (sim / "sim.json").unlink()
        sim.rmdir()
        configured = {"orrery": ExternalRoot(override, "--external-root")}
        errors, _, _, _, _ = run_checks(isolated, configured_external_roots=configured)
        if errors:
            failures.append("explicit-external-precedence: unexpected errors:\n" + "\n".join(errors))

        claims_path = isolated / "theory" / "demo" / "claims.json"
        claims = load_json(claims_path)
        assert isinstance(claims, dict)
        claims["claims"][0]["links"] = ["../../../orrery/lab/sims/missing-sim/"]
        claims_path.write_text(json.dumps(claims, indent=2) + "\n", encoding="utf-8")
        errors, _, _, _, _ = run_checks(isolated, configured_external_roots=configured)
        blob = "\n".join(errors)
        if "link does not resolve: ../../../orrery/lab/sims/missing-sim/" not in blob or str(
            override / "lab" / "sims" / "missing-sim"
        ) not in blob:
            failures.append(f"external-target-missing: inaccurate error:\n{blob}")

        unavailable = {"orrery": ExternalRoot(collection / "absent-orrery", "--external-root")}
        errors, _, _, _, _ = run_checks(isolated, configured_external_roots=unavailable)
        blob = "\n".join(errors)
        if "external checkout 'orrery' is unavailable" not in blob:
            failures.append(f"external-checkout-unavailable: expected distinct error, got:\n{blob}")

    if failures:
        for item in failures:
            print(f"selftest fail: {item}", file=sys.stderr)
        print(f"{len(failures)} selftest failure(s)", file=sys.stderr)
        return 1
    print("selftest ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-ledger", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument(
        "--external-root",
        action="append",
        default=[],
        metavar="NAME=PATH",
        help="map a supported external repository name to its checkout; overrides worktree discovery",
    )
    args = parser.parse_args(argv)
    if args.selftest:
        return selftest()
    root = args.root.resolve()
    try:
        configured_external_roots = parse_external_roots(args.external_root)
    except ValueError as exc:
        parser.error(str(exc))
    errors, expected, _, _, _ = run_checks(root, configured_external_roots=configured_external_roots)
    if args.write_ledger:
        (root / "ledger.md").write_text(expected, encoding="utf-8")
        print(f"wrote {root / 'ledger.md'}")
    else:
        errors.extend(check_ledger(root, expected))
    if errors:
        return fail(errors)
    print("theory check ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
